# REUSE 3.3 (https://reuse.software) — the licence of every file in this
# repository, by path. Assembled by the association's publication lane.
version = 1
SPDX-PackageName = "standard-manifest-oh"
SPDX-PackageSupplier = "Verein OpenHelvetia <admin@openhelvetia.swiss>"
SPDX-PackageDownloadLocation = "https://github.com/OpenHelvetia/standard-manifest-oh"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Verein OpenHelvetia"
SPDX-License-Identifier = "Apache-2.0"
